// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void up_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Splash_screen
void ui_Splash_screen_screen_init(void);
void ui_event_Splash_screen(lv_event_t * e);
lv_obj_t * ui_Splash_screen;
lv_obj_t * ui_logo_label;
lv_obj_t * ui_pain_drain_logo;

// SCREEN: ui_TENS_screen
void ui_TENS_screen_screen_init(void);
void ui_event_TENS_screen(lv_event_t * e);
lv_obj_t * ui_TENS_screen;
lv_obj_t * ui_TENS_label;
lv_obj_t * ui_TENS_slider;
lv_obj_t * ui_low_label;
lv_obj_t * ui_high_label;
lv_obj_t * ui_scrollDotsPg1;
lv_obj_t * ui_dot1Pg1;
lv_obj_t * ui_dot2Pg1;
lv_obj_t * ui_dot3Pg1;
lv_obj_t * ui_dot4Pg1;
lv_obj_t * ui_dot5Pg1;

// SCREEN: ui_Temperature_screen
void ui_Temperature_screen_screen_init(void);
void ui_event_Temperature_screen(lv_event_t * e);
lv_obj_t * ui_Temperature_screen;
lv_obj_t * ui_Temperature_label;
lv_obj_t * ui_scrollDotsPg2;
lv_obj_t * ui_dot1Pg2;
lv_obj_t * ui_dot2Pg2;
lv_obj_t * ui_dot3Pg2;
lv_obj_t * ui_dot4Pg2;
lv_obj_t * ui_dot5Pg2;
lv_obj_t * ui_Temperature_slider;
lv_obj_t * ui_snowflake;
lv_obj_t * ui_fire;

// SCREEN: ui_Vibration_screen
void ui_Vibration_screen_screen_init(void);
void ui_event_Vibration_screen(lv_event_t * e);
lv_obj_t * ui_Vibration_screen;
lv_obj_t * ui_Vibration_label;
lv_obj_t * ui_scrollDotsPg3;
lv_obj_t * ui_dot1Pg3;
lv_obj_t * ui_dot2Pg3;
lv_obj_t * ui_dot3Pg3;
lv_obj_t * ui_dot4Pg3;
lv_obj_t * ui_dot5Pg3;
lv_obj_t * ui_Amplitude_slider;
lv_obj_t * ui_Frequency_slider;
lv_obj_t * ui_Waveform_slider;
lv_obj_t * ui_Amplitude_label;
lv_obj_t * ui_Frequency_label;
lv_obj_t * ui_Waveform_label;
lv_obj_t * ui_Waveform_drop_down_menu;

// SCREEN: ui_Presets_screen
void ui_Presets_screen_screen_init(void);
void ui_event_Presets_screen(lv_event_t * e);
lv_obj_t * ui_Presets_screen;
lv_obj_t * ui_Presets_label;
lv_obj_t * ui_scrollDotsPg4;
lv_obj_t * ui_dot1Pg4;
lv_obj_t * ui_dot2Pg4;
lv_obj_t * ui_dot3Pg4;
lv_obj_t * ui_dot4Pg4;
lv_obj_t * ui_dot5Pg4;
lv_obj_t * ui_Preset_drop_down_menu;
void ui_event_Save_setting_button(lv_event_t * e);
lv_obj_t * ui_Save_setting_button;
lv_obj_t * ui_Save_setting_label;
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_TextArea;

// SCREEN: ui_Brigtness_screen
void ui_Brigtness_screen_screen_init(void);
void ui_event_Brigtness_screen(lv_event_t * e);
lv_obj_t * ui_Brigtness_screen;
lv_obj_t * ui_Brightness_screen;
lv_obj_t * ui_scrollDotsPg5;
lv_obj_t * ui_dot1Pg5;
lv_obj_t * ui_dot2Pg5;
lv_obj_t * ui_dot3Pg5;
lv_obj_t * ui_dot4Pg5;
lv_obj_t * ui_dot5Pg5;
lv_obj_t * ui_Brightness_slider;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void up_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -30, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 100);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Splash_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_TENS_screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 2000, &ui_TENS_screen_screen_init);
    }
}
void ui_event_TENS_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Temperature_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Temperature_screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Vibration_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Vibration_screen_screen_init);
    }
}
void ui_event_Temperature_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TENS_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TENS_screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Vibration_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Vibration_screen_screen_init);
    }
}
void ui_event_Vibration_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Temperature_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Temperature_screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Presets_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Presets_screen_screen_init);
    }
}
void ui_event_Presets_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Vibration_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Vibration_screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Brigtness_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Brigtness_screen_screen_init);
    }
}
void ui_event_Save_setting_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TextArea, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Brigtness_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TENS_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TENS_screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Presets_screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Presets_screen_screen_init);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        up_Animation(ui_pain_drain_logo, 500);
        up_Animation(ui_logo_label, 500);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Splash_screen_screen_init();
    ui_TENS_screen_screen_init();
    ui_Temperature_screen_screen_init();
    ui_Vibration_screen_screen_init();
    ui_Presets_screen_screen_init();
    ui_Brigtness_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_Splash_screen);
}
