// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#ifndef _PAIN_DRAIN_UI_H
#define _PAIN_DRAIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "./lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void up_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash_screen
void ui_Splash_screen_screen_init(void);
void ui_event_Splash_screen(lv_event_t * e);
extern lv_obj_t * ui_Splash_screen;
extern lv_obj_t * ui_logo_label;
extern lv_obj_t * ui_pain_drain_logo;
// SCREEN: ui_TENS_screen
void ui_TENS_screen_screen_init(void);
void ui_event_TENS_screen(lv_event_t * e);
extern lv_obj_t * ui_TENS_screen;
extern lv_obj_t * ui_TENS_label;
extern lv_obj_t * ui_TENS_slider;
extern lv_obj_t * ui_low_label;
extern lv_obj_t * ui_high_label;
extern lv_obj_t * ui_scrollDotsPg1;
extern lv_obj_t * ui_dot1Pg1;
extern lv_obj_t * ui_dot2Pg1;
extern lv_obj_t * ui_dot3Pg1;
extern lv_obj_t * ui_dot4Pg1;
extern lv_obj_t * ui_dot5Pg1;
// SCREEN: ui_Temperature_screen
void ui_Temperature_screen_screen_init(void);
void ui_event_Temperature_screen(lv_event_t * e);
extern lv_obj_t * ui_Temperature_screen;
extern lv_obj_t * ui_Temperature_label;
extern lv_obj_t * ui_scrollDotsPg2;
extern lv_obj_t * ui_dot1Pg2;
extern lv_obj_t * ui_dot2Pg2;
extern lv_obj_t * ui_dot3Pg2;
extern lv_obj_t * ui_dot4Pg2;
extern lv_obj_t * ui_dot5Pg2;
extern lv_obj_t * ui_Temperature_slider;
extern lv_obj_t * ui_snowflake;
extern lv_obj_t * ui_fire;
// SCREEN: ui_Vibration_screen
void ui_Vibration_screen_screen_init(void);
void ui_event_Vibration_screen(lv_event_t * e);
extern lv_obj_t * ui_Vibration_screen;
extern lv_obj_t * ui_Vibration_label;
extern lv_obj_t * ui_scrollDotsPg3;
extern lv_obj_t * ui_dot1Pg3;
extern lv_obj_t * ui_dot2Pg3;
extern lv_obj_t * ui_dot3Pg3;
extern lv_obj_t * ui_dot4Pg3;
extern lv_obj_t * ui_dot5Pg3;
extern lv_obj_t * ui_Amplitude_slider;
extern lv_obj_t * ui_Frequency_slider;
extern lv_obj_t * ui_Waveform_slider;
extern lv_obj_t * ui_Amplitude_label;
extern lv_obj_t * ui_Frequency_label;
extern lv_obj_t * ui_Waveform_label;
extern lv_obj_t * ui_Waveform_drop_down_menu;
// SCREEN: ui_Presets_screen
void ui_Presets_screen_screen_init(void);
void ui_event_Presets_screen(lv_event_t * e);
extern lv_obj_t * ui_Presets_screen;
extern lv_obj_t * ui_Presets_label;
extern lv_obj_t * ui_scrollDotsPg4;
extern lv_obj_t * ui_dot1Pg4;
extern lv_obj_t * ui_dot2Pg4;
extern lv_obj_t * ui_dot3Pg4;
extern lv_obj_t * ui_dot4Pg4;
extern lv_obj_t * ui_dot5Pg4;
extern lv_obj_t * ui_Preset_drop_down_menu;
void ui_event_Save_setting_button(lv_event_t * e);
extern lv_obj_t * ui_Save_setting_button;
extern lv_obj_t * ui_Save_setting_label;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_TextArea;
// SCREEN: ui_Brigtness_screen
void ui_Brigtness_screen_screen_init(void);
void ui_event_Brigtness_screen(lv_event_t * e);
extern lv_obj_t * ui_Brigtness_screen;
extern lv_obj_t * ui_Brightness_screen;
extern lv_obj_t * ui_scrollDotsPg5;
extern lv_obj_t * ui_dot1Pg5;
extern lv_obj_t * ui_dot2Pg5;
extern lv_obj_t * ui_dot3Pg5;
extern lv_obj_t * ui_dot4Pg5;
extern lv_obj_t * ui_dot5Pg5;
extern lv_obj_t * ui_Brightness_slider;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(
    ui_img_paindraindevicewithoutbackgroundresized_png);    // assets\PainDrainDeviceWithoutBackgroundResized.png
LV_IMG_DECLARE(ui_img_snowflake_icon_small_png);    // assets\snowflake icon small.png
LV_IMG_DECLARE(ui_img_fire_icon_small_png);    // assets\fire icon small.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
