#ifndef BOOTLOADER_VERSION_H
#define BOOTLOADER_VERSION_H

#define APP0_VERSION_MAJOR 1
#define APP0_VERSION_MINOR 0
#define APP0_VERSION_PATCH 0
#define APP0_VERSION_STR   "1.0.0"

#endif /* BOOTLOADER_VERSION_H */
