/** 
 * Driver for BQ24298 Charger device

 */


#include <project.h>


#define BQ24298_I2C_ADDR 0x6B


#define CHG_IN_SRC_CTRL_REG 0
    
    #define CHG_IN_SRC_CTRL_IINLIM_START 0
    #define CHG_IN_SRC_CTRL_IINLIM_SIZE 3
    #define CHG_IN_SRC_CTRL_IINLIM_MASK 0x07
    
    #define CHG_IN_SRC_CTRL_VINDPM_START 3
    #define CHG_IN_SRC_CTRL_VINDPM_SIZE 4
    #define CHG_IN_SRC_CTRL_VINDPM_MASK 0x78
    
    #define CHG_IN_SRC_CTRL_ENHIZ_START 7
    #define CHG_IN_SRC_CTRL_ENHIZ_SIZE 1
    #define CHG_IN_SRC_CTRL_ENHIZ_MASK 0x80

#define CHG_PWR_ON_CFG_REG 1
    
    #define CHG_PWR_ON_CFG_BOOSTLIM_START 0
    #define CHG_PWR_ON_CFG_BOOSTLIM_SIZE 1
    #define CHG_PWR_ON_CFG_BOOSTLIM_MASK 0x01
    
    #define CHG_PWR_ON_CFG_SYSMIN_START 1
    #define CHG_PWR_ON_CFG_SYSMIN_SIZE 3
    #define CHG_PWR_ON_CFG_SYSMIN_MASK 0x0E
    
    #define CHG_PWR_ON_CFG_CHGCONFIG_START 4
    #define CHG_PWR_ON_CFG_CHGCONFIG_SIZE 1
    #define CHG_PWR_ON_CFG_CHGCONFIG_MASK 0x10
    
    #define CHG_PWR_ON_CFG_OTGCONFIG_START 5
    #define CHG_PWR_ON_CFG_OTGCONFIG_SIZE 1
    #define CHG_PWR_ON_CFG_OTGCONFIG_MASK 0x20
    
    #define CHG_PWR_ON_CFG_WDTRST_START 6
    #define CHG_PWR_ON_CFG_WDTRST_SIZE 1
    #define CHG_PWR_ON_CFG_WDTRST_MASK 0x40

    #define CHG_PWR_ON_CFG_REGRST_START 7
    #define CHG_PWR_ON_CFG_REGRST_SIZE 1
    #define CHG_PWR_ON_CFG_REGRST_MASK 0x80

    
#define CHG_CUR_CTRL_REG 2
    
    #define CHG_CUR_CTRL_FRCE20PCT_START 0
    #define CHG_CUR_CTRL_FRCE20PCT_SIZE 1
    #define CHG_CUR_CTRL_FRCE20PCT_MASK 0x01
    
    #define CHG_CUR_CTRL_BCLD_START 1
    #define CHG_CUR_CTRL_BCLD_SIZE 1
    #define CHG_CUR_CTRL_BCLD_MASK 0x02
    
    #define CHG_CUR_CTRL_ICHG_START 2
    #define CHG_CUR_CTRL_ICHG_SIZE 6
    #define CHG_CUR_CTRL_ICHG_MASK 0xFC
    
 #define CHG_PRE_CHG_TERM_CUR_CTRL_REG 3
    
    #define CHG_PRE_CHG_TERMP_CUR_CTRL_ITERM_START 0
    #define CHG_PRE_CHG_TERMP_CUR_CTRL_ITERM_SIZE 3
    #define CHG_PRE_CHG_TERMP_CUR_CTRL_ITERM_MASK 0x07
    
    #define CHG_PRE_CHG_TERMP_CUR_CTRL_IPRECHG_START 4
    #define CHG_PRE_CHG_TERMP_CUR_CTRL_IPRECHG_SIZE 4
    #define CHG_PRE_CHG_TERMP_CUR_CTRL_IPRECHG_MASK 0xF0
    
#define CHG_VOLTS_CTRL_REG 4
    
    #define CHG_VOLTS_CTRL_VRECHG_START 0
    #define CHG_VOLTS_CTRL_VRECHG_SIZE 1
    #define CHG_VOLTS_CTRL_VRECHG_MASK 0x01
    
    #define CHG_VOLTS_CTRL_BATLOWV_START 1
    #define CHG_VOLTS_CTRL_BATLOWV_SIZE 1
    #define CHG_VOLTS_CTRL_BATLOWV_MASK 0x02
    
    #define CHG_VOLTS_CTRL_VREG_START 2
    #define CHG_VOLTS_CTRL_VREG_SIZE 6
    #define CHG_VOLTS_CTRL_VREG_MASK 0xFC
    
    
#define CHG_CHG_TERM_TMR_CTRL_REG 5 
    
    #define CHG_CHG_TERM_TMR_CTRL_CHGTMR_START 1
    #define CHG_CHG_TERM_TMR_CTRL_CHGTMR_SIZE 2
    #define CHG_CHG_TERM_TMR_CTRL_CHGTMR_MASK 0x06
    
    #define CHG_CHG_TERM_TMR_CTRL_ENTMR_START 3
    #define CHG_CHG_TERM_TMR_CTRL_ENTMR_SIZE 1
    #define CHG_CHG_TERM_TMR_CTRL_ENTMR_MASK 0x08
    
    #define CHG_CHG_TERM_TMR_CTRL_WDT_START 4
    #define CHG_CHG_TERM_TMR_CTRL_WDT_SIZE 2
    #define CHG_CHG_TERM_TMR_CTRL_WDT_MASK 0x30
    
    #define CHG_CHG_TERM_TMR_CTRL_ENTERM_START 7
    #define CHG_CHG_TERM_TMR_CTRL_ENTERM_SIZE 1
    #define CHG_CHG_TERM_TMR_CTRL_ENTERM_MASK 0x80
    
#define CHG_BST_V_THERM_REG_CTRL_REG 6
    
    #define CHG_BST_V_THERM_REG_CTRL_TREG_START 0
    #define CHG_BST_V_THERM_REG_CTRL_TREG_SIZE 2
    #define CHG_BST_V_THERM_REG_CTRL_TREG_MASK 0x03
    
    #define CHG_BST_V_THERM_REG_CTRL_BHOT_START 2
    #define CHG_BST_V_THERM_REG_CTRL_BHOT_SIZE 2
    #define CHG_BST_V_THERM_REG_CTRL_BHOT_MASK 0x0C
    
    #define CHG_BST_V_THERM_REG_CTRL_BOOSTV_START 4
    #define CHG_BST_V_THERM_REG_CTRL_BOOSTV_SIZE 4
    #define CHG_BST_V_THERM_REG_CTRL_BOOSTV_MASK 0xF0
    
#define CHG_MISC_OP_CTRL_REG 7
    
    #define CHG_MISC_OP_CTRL_INTMASK_START 0
    #define CHG_MISC_OP_CTRL_INTMASK_SIZE 2
    #define CHG_MISC_OP_CTRL_INTMASK_MASK 0x03
    
    #define CHG_MISC_OP_CTRL_BTFETDIS_START 5
    #define CHG_MISC_OP_CTRL_BTFETDIS_SIZE 1
    #define CHG_MISC_OP_CTRL_BTFETDIS_MASK 0x20
    
    #define CHG_MISC_OP_CTRL_TMR2XEN_START 6
    #define CHG_MISC_OP_CTRL_TMR2XEN_SIZE 1
    #define CHG_MISC_OP_CTRL_TMR2XEN_MASK 0x40 
    
    #define CHG_MISC_OP_CTRL_DPDMEN_START 7
    #define CHG_MISC_OP_CTRL_DPDMEN_SIZE 1
    #define CHG_MISC_OP_CTRL_DPDMEN_MASK 0x80

    
#define CHG_SYS_STAT_REG 8
    
    #define CHG_SYS_STAT_VSYS_START 0
    #define CHG_SYS_STAT_VSYS_SIZE 1
    #define CHG_SYS_STAT_VSYS_MASK 0x01
    
    #define CHG_SYS_STAT_THERM_START 1
    #define CHG_SYS_STAT_THERM_SIZE 1
    #define CHG_SYS_STAT_THERM_MASK 0x02
    
    #define CHG_SYS_STAT_PGM_START 2
    #define CHG_SYS_STAT_PGM_SIZE 1
    #define CHG_SYS_STAT_PGM_MASK 0x04
    
    #define CHG_SYS_STAT_DPM_START 3
    #define CHG_SYS_STAT_DPM_SIZE 1
    #define CHG_SYS_STAT_DPM_MASK 0x08
    
    #define CHG_SYS_STAT_CHG_START 4
    #define CHG_SYS_STAT_CHG_SIZE 2
    #define CHG_SYS_STAT_CHG_MASK 0x30
    
    #define CHG_SYS_STAT_VBUS_START 6
    #define CHG_SYS_STAT_VBUS_SIZE 2
    #define CHG_SYS_STAT_VBUS_MASK 0xF0
    
#define CHG_NEW_FAULT_REG 9
    
    #define CHG_NEW_FAULT_NTC_START 0
    #define CHG_NEW_FAULT_NTC_SIZE 2
    #define CHG_NEW_FAULT_NTC_MASK 0x03
    
    #define CHG_NEW_FAULT_BATT_START 3
    #define CHG_NEW_FAULT_BATT_SIZE 1
    #define CHG_NEW_FAULT_BATT_MASK 0x08
    
    #define CHG_NEW_FAULT_CHG_START 4
    #define CHG_NEW_FAULT_CHG_SIZE 2
    #define CHG_NEW_FAULT_CHG_MASK 0x03
    
    #define CHG_NEW_FAULT_OTG_START 6
    #define CHG_NEW_FAULT_OTG_SIZE 1
    #define CHG_NEW_FAULT_OTG_MASK 0x40
    
    #define CHG_NEW_FAULT_WDT_START 7
    #define CHG_NEW_FAULT_WDT_SIZE 1
    #define CHG_NEW_FAULT_WDT_MASK 0x80
    
#define CHG_VNDR_PART_REV_REG 10
    
    #define CHG_VNDR_PART_REV_REV_START 0
    #define CHG_VNDR_PART_REV_REV_SIZE 3
    #define CHG_VNDR_PART_REV_REV_MASK 0x07
    
    #define CHG_VNDR_PART_REV_PN_START 5
    #define CHG_VNDR_PART_REV_PN_SIZE 3
    #define CHG_VNDR_PART_REV_PN_MASK 0xE0
    
    

void bq24298_init( void );
void bq24298_write_reg(int reg, int d);
void bq24298_read_reg(uint8_t reg, uint8_t* d, int num_regs);
