#ifndef VERSION_H
#define VERSION_H

#define FIRMWARE_VERSION_MAJOR  1
#define FIRMWARE_VERSION_MINOR  0
#define FIRMWARE_VERSION_PATCH  0

#define FIRMWARE_VERSION_STR    "1.0.0"

#endif /* VERSION_H */
