// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#include "../ui.h"

void ui_Brigtness_screen_screen_init(void)
{
    ui_Brigtness_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Brigtness_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Brigtness_screen, lv_color_hex(0x615A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Brigtness_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Brigtness_screen, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Brigtness_screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness_screen = lv_label_create(ui_Brigtness_screen);
    lv_obj_set_width(ui_Brightness_screen, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Brightness_screen, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Brightness_screen, -4);
    lv_obj_set_y(ui_Brightness_screen, lv_pct(12));
    lv_obj_set_align(ui_Brightness_screen, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Brightness_screen, "Brightness");
    lv_obj_set_style_text_font(ui_Brightness_screen, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrollDotsPg5 = lv_obj_create(ui_Brigtness_screen);
    lv_obj_set_width(ui_scrollDotsPg5, 145);
    lv_obj_set_height(ui_scrollDotsPg5, 30);
    lv_obj_set_x(ui_scrollDotsPg5, 0);
    lv_obj_set_y(ui_scrollDotsPg5, -15);
    lv_obj_set_align(ui_scrollDotsPg5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_scrollDotsPg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrollDotsPg5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrollDotsPg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrollDotsPg5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrollDotsPg5, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrollDotsPg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_scrollDotsPg5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_scrollDotsPg5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1Pg5 = lv_obj_create(ui_scrollDotsPg5);
    lv_obj_set_width(ui_dot1Pg5, 20);
    lv_obj_set_height(ui_dot1Pg5, 20);
    lv_obj_set_x(ui_dot1Pg5, -60);
    lv_obj_set_y(ui_dot1Pg5, 10);
    lv_obj_set_align(ui_dot1Pg5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot1Pg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot1Pg5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot1Pg5, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot1Pg5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2Pg5 = lv_obj_create(ui_scrollDotsPg5);
    lv_obj_set_width(ui_dot2Pg5, 20);
    lv_obj_set_height(ui_dot2Pg5, 20);
    lv_obj_set_x(ui_dot2Pg5, -30);
    lv_obj_set_y(ui_dot2Pg5, 10);
    lv_obj_set_align(ui_dot2Pg5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot2Pg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot2Pg5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot2Pg5, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot2Pg5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3Pg5 = lv_obj_create(ui_scrollDotsPg5);
    lv_obj_set_width(ui_dot3Pg5, 20);
    lv_obj_set_height(ui_dot3Pg5, 20);
    lv_obj_set_x(ui_dot3Pg5, 0);
    lv_obj_set_y(ui_dot3Pg5, 10);
    lv_obj_set_align(ui_dot3Pg5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot3Pg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot3Pg5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot3Pg5, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot3Pg5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4Pg5 = lv_obj_create(ui_scrollDotsPg5);
    lv_obj_set_width(ui_dot4Pg5, 20);
    lv_obj_set_height(ui_dot4Pg5, 20);
    lv_obj_set_x(ui_dot4Pg5, 30);
    lv_obj_set_y(ui_dot4Pg5, 10);
    lv_obj_set_align(ui_dot4Pg5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot4Pg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot4Pg5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot4Pg5, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot4Pg5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5Pg5 = lv_obj_create(ui_scrollDotsPg5);
    lv_obj_set_width(ui_dot5Pg5, 20);
    lv_obj_set_height(ui_dot5Pg5, 20);
    lv_obj_set_x(ui_dot5Pg5, 60);
    lv_obj_set_y(ui_dot5Pg5, 10);
    lv_obj_set_align(ui_dot5Pg5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot5Pg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot5Pg5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot5Pg5, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot5Pg5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness_slider = lv_slider_create(ui_Brigtness_screen);
    lv_slider_set_range(ui_Brightness_slider, 0, 10);
    lv_slider_set_value(ui_Brightness_slider, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Brightness_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Brightness_slider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_Brightness_slider, 150);
    lv_obj_set_height(ui_Brightness_slider, 15);
    lv_obj_set_align(ui_Brightness_slider, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Brigtness_screen, ui_event_Brigtness_screen, LV_EVENT_ALL, NULL);

}
