// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#include "../ui.h"

void ui_Presets_screen_screen_init(void)
{
    ui_Presets_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Presets_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Presets_screen, lv_color_hex(0x615A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Presets_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Presets_screen, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Presets_screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Presets_label = lv_label_create(ui_Presets_screen);
    lv_obj_set_width(ui_Presets_label, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Presets_label, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Presets_label, -4);
    lv_obj_set_y(ui_Presets_label, lv_pct(12));
    lv_obj_set_align(ui_Presets_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Presets_label, "Presets");
    lv_obj_set_style_text_font(ui_Presets_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrollDotsPg4 = lv_obj_create(ui_Presets_screen);
    lv_obj_set_width(ui_scrollDotsPg4, 145);
    lv_obj_set_height(ui_scrollDotsPg4, 30);
    lv_obj_set_x(ui_scrollDotsPg4, 0);
    lv_obj_set_y(ui_scrollDotsPg4, -15);
    lv_obj_set_align(ui_scrollDotsPg4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_scrollDotsPg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrollDotsPg4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrollDotsPg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrollDotsPg4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrollDotsPg4, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrollDotsPg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_scrollDotsPg4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_scrollDotsPg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1Pg4 = lv_obj_create(ui_scrollDotsPg4);
    lv_obj_set_width(ui_dot1Pg4, 20);
    lv_obj_set_height(ui_dot1Pg4, 20);
    lv_obj_set_x(ui_dot1Pg4, -60);
    lv_obj_set_y(ui_dot1Pg4, 10);
    lv_obj_set_align(ui_dot1Pg4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot1Pg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot1Pg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot1Pg4, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot1Pg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2Pg4 = lv_obj_create(ui_scrollDotsPg4);
    lv_obj_set_width(ui_dot2Pg4, 20);
    lv_obj_set_height(ui_dot2Pg4, 20);
    lv_obj_set_x(ui_dot2Pg4, -30);
    lv_obj_set_y(ui_dot2Pg4, 10);
    lv_obj_set_align(ui_dot2Pg4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot2Pg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot2Pg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot2Pg4, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot2Pg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3Pg4 = lv_obj_create(ui_scrollDotsPg4);
    lv_obj_set_width(ui_dot3Pg4, 20);
    lv_obj_set_height(ui_dot3Pg4, 20);
    lv_obj_set_x(ui_dot3Pg4, 0);
    lv_obj_set_y(ui_dot3Pg4, 10);
    lv_obj_set_align(ui_dot3Pg4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot3Pg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot3Pg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot3Pg4, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot3Pg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4Pg4 = lv_obj_create(ui_scrollDotsPg4);
    lv_obj_set_width(ui_dot4Pg4, 20);
    lv_obj_set_height(ui_dot4Pg4, 20);
    lv_obj_set_x(ui_dot4Pg4, 30);
    lv_obj_set_y(ui_dot4Pg4, 10);
    lv_obj_set_align(ui_dot4Pg4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot4Pg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot4Pg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot4Pg4, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot4Pg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5Pg4 = lv_obj_create(ui_scrollDotsPg4);
    lv_obj_set_width(ui_dot5Pg4, 20);
    lv_obj_set_height(ui_dot5Pg4, 20);
    lv_obj_set_x(ui_dot5Pg4, 60);
    lv_obj_set_y(ui_dot5Pg4, 10);
    lv_obj_set_align(ui_dot5Pg4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot5Pg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot5Pg4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot5Pg4, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot5Pg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_drop_down_menu = lv_dropdown_create(ui_Presets_screen);
    lv_dropdown_set_options(ui_Preset_drop_down_menu, "Option 1\nOption 2\nOption 3\nOption 4");
    lv_obj_set_width(ui_Preset_drop_down_menu, 150);
    lv_obj_set_height(ui_Preset_drop_down_menu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset_drop_down_menu, 0);
    lv_obj_set_y(ui_Preset_drop_down_menu, -60);
    lv_obj_set_align(ui_Preset_drop_down_menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Preset_drop_down_menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Save_setting_button = lv_btn_create(ui_Presets_screen);
    lv_obj_set_width(ui_Save_setting_button, 100);
    lv_obj_set_height(ui_Save_setting_button, 50);
    lv_obj_set_x(ui_Save_setting_button, 0);
    lv_obj_set_y(ui_Save_setting_button, 65);
    lv_obj_set_align(ui_Save_setting_button, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Save_setting_button, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_Save_setting_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Save_setting_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Save_setting_button, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Save_setting_button, lv_color_hex(0x28BDE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save_setting_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Save_setting_button, lv_color_hex(0x124D76), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Save_setting_button, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Save_setting_button, lv_color_hex(0xF42222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Save_setting_button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Save_setting_label = lv_label_create(ui_Presets_screen);
    lv_obj_set_width(ui_Save_setting_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Save_setting_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Save_setting_label, 0);
    lv_obj_set_y(ui_Save_setting_label, 65);
    lv_obj_set_align(ui_Save_setting_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Save_setting_label, "Save Setting");

    ui_Keyboard = lv_keyboard_create(ui_Presets_screen);
    lv_obj_set_width(ui_Keyboard, 240);
    lv_obj_set_height(ui_Keyboard, 133);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TextArea = lv_textarea_create(ui_Presets_screen);
    lv_obj_set_width(ui_TextArea, 150);
    lv_obj_set_height(ui_TextArea, 70);
    lv_obj_set_x(ui_TextArea, 0);
    lv_obj_set_y(ui_TextArea, -10);
    lv_obj_set_align(ui_TextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea, "Placeholder...");
    lv_obj_add_flag(ui_TextArea, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Save_setting_button, ui_event_Save_setting_button, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_TextArea);
    lv_obj_add_event_cb(ui_Presets_screen, ui_event_Presets_screen, LV_EVENT_ALL, NULL);

}
