// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#include "../ui.h"

void ui_Splash_screen_screen_init(void)
{
    ui_Splash_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash_screen, lv_color_hex(0x615A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Splash_screen, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Splash_screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo_label = lv_label_create(ui_Splash_screen);
    lv_obj_set_width(ui_logo_label, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_logo_label, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_logo_label, 0);
    lv_obj_set_y(ui_logo_label, lv_pct(20));
    lv_obj_set_align(ui_logo_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logo_label, "Pain Drain");
    lv_obj_set_style_text_font(ui_logo_label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pain_drain_logo = lv_img_create(ui_Splash_screen);
    lv_img_set_src(ui_pain_drain_logo, &ui_img_paindraindevicewithoutbackgroundresized_png);
    lv_obj_set_width(ui_pain_drain_logo, LV_SIZE_CONTENT);   /// 167
    lv_obj_set_height(ui_pain_drain_logo, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_pain_drain_logo, 0);
    lv_obj_set_y(ui_pain_drain_logo, -55);
    lv_obj_set_align(ui_pain_drain_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pain_drain_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pain_drain_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Splash_screen, ui_event_Splash_screen, LV_EVENT_ALL, NULL);

}
