// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#include "../ui.h"

void ui_TENS_screen_screen_init(void)
{
    ui_TENS_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TENS_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TENS_screen, lv_color_hex(0x615A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TENS_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TENS_screen, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TENS_screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TENS_label = lv_label_create(ui_TENS_screen);
    lv_obj_set_width(ui_TENS_label, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_TENS_label, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_TENS_label, -4);
    lv_obj_set_y(ui_TENS_label, lv_pct(12));
    lv_obj_set_align(ui_TENS_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TENS_label, "TENS");
    lv_obj_set_style_text_font(ui_TENS_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TENS_slider = lv_slider_create(ui_TENS_screen);
    lv_obj_set_width(ui_TENS_slider, 150);
    lv_obj_set_height(ui_TENS_slider, 15);
    lv_obj_set_align(ui_TENS_slider, LV_ALIGN_CENTER);

    ui_low_label = lv_label_create(ui_TENS_screen);
    lv_obj_set_width(ui_low_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_low_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_low_label, -74);
    lv_obj_set_y(ui_low_label, 31);
    lv_obj_set_align(ui_low_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_low_label, "1");

    ui_high_label = lv_label_create(ui_TENS_screen);
    lv_obj_set_width(ui_high_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_high_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_high_label, 66);
    lv_obj_set_y(ui_high_label, 31);
    lv_obj_set_align(ui_high_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_high_label, "10");

    ui_scrollDotsPg1 = lv_obj_create(ui_TENS_screen);
    lv_obj_set_width(ui_scrollDotsPg1, 145);
    lv_obj_set_height(ui_scrollDotsPg1, 30);
    lv_obj_set_x(ui_scrollDotsPg1, 0);
    lv_obj_set_y(ui_scrollDotsPg1, -15);
    lv_obj_set_align(ui_scrollDotsPg1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_scrollDotsPg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrollDotsPg1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrollDotsPg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrollDotsPg1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrollDotsPg1, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrollDotsPg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_scrollDotsPg1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_scrollDotsPg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1Pg1 = lv_obj_create(ui_scrollDotsPg1);
    lv_obj_set_width(ui_dot1Pg1, 20);
    lv_obj_set_height(ui_dot1Pg1, 20);
    lv_obj_set_x(ui_dot1Pg1, -60);
    lv_obj_set_y(ui_dot1Pg1, 10);
    lv_obj_set_align(ui_dot1Pg1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot1Pg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot1Pg1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot1Pg1, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot1Pg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2Pg1 = lv_obj_create(ui_scrollDotsPg1);
    lv_obj_set_width(ui_dot2Pg1, 20);
    lv_obj_set_height(ui_dot2Pg1, 20);
    lv_obj_set_x(ui_dot2Pg1, -30);
    lv_obj_set_y(ui_dot2Pg1, 10);
    lv_obj_set_align(ui_dot2Pg1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot2Pg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot2Pg1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot2Pg1, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot2Pg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3Pg1 = lv_obj_create(ui_scrollDotsPg1);
    lv_obj_set_width(ui_dot3Pg1, 20);
    lv_obj_set_height(ui_dot3Pg1, 20);
    lv_obj_set_x(ui_dot3Pg1, 0);
    lv_obj_set_y(ui_dot3Pg1, 10);
    lv_obj_set_align(ui_dot3Pg1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot3Pg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot3Pg1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot3Pg1, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot3Pg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4Pg1 = lv_obj_create(ui_scrollDotsPg1);
    lv_obj_set_width(ui_dot4Pg1, 20);
    lv_obj_set_height(ui_dot4Pg1, 20);
    lv_obj_set_x(ui_dot4Pg1, 30);
    lv_obj_set_y(ui_dot4Pg1, 10);
    lv_obj_set_align(ui_dot4Pg1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot4Pg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot4Pg1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot4Pg1, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot4Pg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5Pg1 = lv_obj_create(ui_scrollDotsPg1);
    lv_obj_set_width(ui_dot5Pg1, 20);
    lv_obj_set_height(ui_dot5Pg1, 20);
    lv_obj_set_x(ui_dot5Pg1, 60);
    lv_obj_set_y(ui_dot5Pg1, 10);
    lv_obj_set_align(ui_dot5Pg1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot5Pg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot5Pg1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot5Pg1, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot5Pg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TENS_screen, ui_event_TENS_screen, LV_EVENT_ALL, NULL);

}
