// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Pain Drain

#include "../ui.h"

void ui_Vibration_screen_screen_init(void)
{
    ui_Vibration_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Vibration_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Vibration_screen, lv_color_hex(0x615A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Vibration_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Vibration_screen, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Vibration_screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vibration_label = lv_label_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Vibration_label, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Vibration_label, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Vibration_label, -4);
    lv_obj_set_y(ui_Vibration_label, lv_pct(12));
    lv_obj_set_align(ui_Vibration_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Vibration_label, "Vibration");
    lv_obj_set_style_text_font(ui_Vibration_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrollDotsPg3 = lv_obj_create(ui_Vibration_screen);
    lv_obj_set_width(ui_scrollDotsPg3, 145);
    lv_obj_set_height(ui_scrollDotsPg3, 30);
    lv_obj_set_x(ui_scrollDotsPg3, 0);
    lv_obj_set_y(ui_scrollDotsPg3, -15);
    lv_obj_set_align(ui_scrollDotsPg3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_scrollDotsPg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrollDotsPg3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrollDotsPg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrollDotsPg3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrollDotsPg3, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrollDotsPg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_scrollDotsPg3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_scrollDotsPg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1Pg3 = lv_obj_create(ui_scrollDotsPg3);
    lv_obj_set_width(ui_dot1Pg3, 20);
    lv_obj_set_height(ui_dot1Pg3, 20);
    lv_obj_set_x(ui_dot1Pg3, -60);
    lv_obj_set_y(ui_dot1Pg3, 10);
    lv_obj_set_align(ui_dot1Pg3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot1Pg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot1Pg3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot1Pg3, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot1Pg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2Pg3 = lv_obj_create(ui_scrollDotsPg3);
    lv_obj_set_width(ui_dot2Pg3, 20);
    lv_obj_set_height(ui_dot2Pg3, 20);
    lv_obj_set_x(ui_dot2Pg3, -30);
    lv_obj_set_y(ui_dot2Pg3, 10);
    lv_obj_set_align(ui_dot2Pg3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot2Pg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot2Pg3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot2Pg3, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot2Pg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3Pg3 = lv_obj_create(ui_scrollDotsPg3);
    lv_obj_set_width(ui_dot3Pg3, 20);
    lv_obj_set_height(ui_dot3Pg3, 20);
    lv_obj_set_x(ui_dot3Pg3, 0);
    lv_obj_set_y(ui_dot3Pg3, 10);
    lv_obj_set_align(ui_dot3Pg3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot3Pg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot3Pg3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot3Pg3, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot3Pg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4Pg3 = lv_obj_create(ui_scrollDotsPg3);
    lv_obj_set_width(ui_dot4Pg3, 20);
    lv_obj_set_height(ui_dot4Pg3, 20);
    lv_obj_set_x(ui_dot4Pg3, 30);
    lv_obj_set_y(ui_dot4Pg3, 10);
    lv_obj_set_align(ui_dot4Pg3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot4Pg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot4Pg3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot4Pg3, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot4Pg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5Pg3 = lv_obj_create(ui_scrollDotsPg3);
    lv_obj_set_width(ui_dot5Pg3, 20);
    lv_obj_set_height(ui_dot5Pg3, 20);
    lv_obj_set_x(ui_dot5Pg3, 60);
    lv_obj_set_y(ui_dot5Pg3, 10);
    lv_obj_set_align(ui_dot5Pg3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_dot5Pg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot5Pg3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot5Pg3, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot5Pg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amplitude_slider = lv_slider_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Amplitude_slider, 150);
    lv_obj_set_height(ui_Amplitude_slider, 15);
    lv_obj_set_x(ui_Amplitude_slider, 0);
    lv_obj_set_y(ui_Amplitude_slider, -70);
    lv_obj_set_align(ui_Amplitude_slider, LV_ALIGN_CENTER);

    ui_Frequency_slider = lv_slider_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Frequency_slider, 150);
    lv_obj_set_height(ui_Frequency_slider, 15);
    lv_obj_set_x(ui_Frequency_slider, 0);
    lv_obj_set_y(ui_Frequency_slider, -15);
    lv_obj_set_align(ui_Frequency_slider, LV_ALIGN_CENTER);

    ui_Waveform_slider = lv_slider_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Waveform_slider, 150);
    lv_obj_set_height(ui_Waveform_slider, 15);
    lv_obj_set_x(ui_Waveform_slider, 0);
    lv_obj_set_y(ui_Waveform_slider, 40);
    lv_obj_set_align(ui_Waveform_slider, LV_ALIGN_CENTER);

    ui_Amplitude_label = lv_label_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Amplitude_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amplitude_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Amplitude_label, -40);
    lv_obj_set_y(ui_Amplitude_label, -45);
    lv_obj_set_align(ui_Amplitude_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Amplitude_label, "Amplitude");

    ui_Frequency_label = lv_label_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Frequency_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Frequency_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Frequency_label, -40);
    lv_obj_set_y(ui_Frequency_label, 10);
    lv_obj_set_align(ui_Frequency_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Frequency_label, "Frequency");

    ui_Waveform_label = lv_label_create(ui_Vibration_screen);
    lv_obj_set_width(ui_Waveform_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Waveform_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Waveform_label, -40);
    lv_obj_set_y(ui_Waveform_label, 75);
    lv_obj_set_align(ui_Waveform_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Waveform_label, "Wavefrom");

    ui_Waveform_drop_down_menu = lv_dropdown_create(ui_Vibration_screen);
    lv_dropdown_set_options(ui_Waveform_drop_down_menu, "Sine\nSquare\nTriangle\nSawtooth");
    lv_obj_set_width(ui_Waveform_drop_down_menu, 100);
    lv_obj_set_height(ui_Waveform_drop_down_menu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Waveform_drop_down_menu, 50);
    lv_obj_set_y(ui_Waveform_drop_down_menu, 75);
    lv_obj_set_align(ui_Waveform_drop_down_menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Waveform_drop_down_menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_Vibration_screen, ui_event_Vibration_screen, LV_EVENT_ALL, NULL);

}
