/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* SW2 */
#define SW2_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define SW2_0_INBUF_ENABLED 1u
#define SW2_0_INIT_DRIVESTATE 1u
#define SW2_0_INIT_MUXSEL 0u
#define SW2_0_INPUT_SYNC 2u
#define SW2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SW2_0_NUM 4u
#define SW2_0_PORT GPIO_PRT0
#define SW2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SW2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SW2_DRIVEMODE CY_GPIO_DM_PULLUP
#define SW2_INBUF_ENABLED 1u
#define SW2_INIT_DRIVESTATE 1u
#define SW2_INIT_MUXSEL 0u
#define SW2_INPUT_SYNC 2u
#define SW2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SW2_NUM 4u
#define SW2_PORT GPIO_PRT0
#define SW2_SLEWRATE CY_GPIO_SLEW_FAST
#define SW2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Alert_LED */
#define Alert_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_0_INBUF_ENABLED 0u
#define Alert_LED_0_INIT_DRIVESTATE 1u
#define Alert_LED_0_INIT_MUXSEL 0u
#define Alert_LED_0_INPUT_SYNC 2u
#define Alert_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_0_NUM 3u
#define Alert_LED_0_PORT GPIO_PRT6
#define Alert_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Alert_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_INBUF_ENABLED 0u
#define Alert_LED_INIT_DRIVESTATE 1u
#define Alert_LED_INIT_MUXSEL 0u
#define Alert_LED_INPUT_SYNC 2u
#define Alert_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_NUM 3u
#define Alert_LED_PORT GPIO_PRT6
#define Alert_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Disconnect_LED */
#define Disconnect_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_0_INBUF_ENABLED 0u
#define Disconnect_LED_0_INIT_DRIVESTATE 1u
#define Disconnect_LED_0_INIT_MUXSEL 0u
#define Disconnect_LED_0_INPUT_SYNC 2u
#define Disconnect_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_0_NUM 5u
#define Disconnect_LED_0_PORT GPIO_PRT0
#define Disconnect_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Disconnect_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_INBUF_ENABLED 0u
#define Disconnect_LED_INIT_DRIVESTATE 1u
#define Disconnect_LED_INIT_MUXSEL 0u
#define Disconnect_LED_INPUT_SYNC 2u
#define Disconnect_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_NUM 5u
#define Disconnect_LED_PORT GPIO_PRT0
#define Disconnect_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Advertising_LED */
#define Advertising_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_0_INBUF_ENABLED 0u
#define Advertising_LED_0_INIT_DRIVESTATE 1u
#define Advertising_LED_0_INIT_MUXSEL 0u
#define Advertising_LED_0_INPUT_SYNC 2u
#define Advertising_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_0_NUM 1u
#define Advertising_LED_0_PORT GPIO_PRT7
#define Advertising_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Advertising_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_INBUF_ENABLED 0u
#define Advertising_LED_INIT_DRIVESTATE 1u
#define Advertising_LED_INIT_MUXSEL 0u
#define Advertising_LED_INPUT_SYNC 2u
#define Advertising_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_NUM 1u
#define Advertising_LED_PORT GPIO_PRT7
#define Advertising_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
