# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Projects\PainDrain\firmware\CE217637_BLE_Find_Me01\PainDrain.cydsn\PainDrain.cyprj
# Date: Fri, 17 Nov 2023 16:46:45 GMT
#set_units -time ns
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyClk_LF} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyFLL} -period 20 -waveform {0 10} [list [get_pins {ClockBlock/fll}]]
create_clock -name {CyClk_HF0} -period 20 -waveform {0 10} [list [get_pins {ClockBlock/hfclk_0}]]
create_clock -name {CyClk_Fast} -period 20 -waveform {0 10} [list [get_pins {ClockBlock/fastclk}]]
create_clock -name {CyClk_Peri} -period 40 -waveform {0 20} [list [get_pins {ClockBlock/periclk}]]
create_generated_clock -name {CyClk_Slow} -source [get_pins {ClockBlock/periclk}] -edges {1 2 3} [list [get_pins {ClockBlock/slowclk}]]
create_clock -name {CyPeriClk_App} -period 40 -waveform {0 20} [list [get_pins {ClockBlock/periclk_App}]]
create_clock -name {CyIMO} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/imo}]]


# Component constraints for C:\Projects\PainDrain\firmware\CE217637_BLE_Find_Me01\PainDrain.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Projects\PainDrain\firmware\CE217637_BLE_Find_Me01\PainDrain.cydsn\PainDrain.cyprj
# Date: Fri, 17 Nov 2023 16:46:37 GMT
