/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* WDTIsr */
#define WDTIsr__INTC_CORTEXM4_ASSIGNED 1
#define WDTIsr__INTC_CORTEXM4_PRIORITY 7u
#define WDTIsr__INTC_NUMBER 22u
#define WDTIsr_INTC_CORTEXM4_ASSIGNED 1
#define WDTIsr_INTC_CORTEXM4_PRIORITY 7u
#define WDTIsr_INTC_NUMBER 22u

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* gpio_irq */
#define gpio_irq__INTC_CORTEXM4_ASSIGNED 1
#define gpio_irq__INTC_CORTEXM4_PRIORITY 7u
#define gpio_irq__INTC_NUMBER 10u
#define gpio_irq_INTC_CORTEXM4_ASSIGNED 1
#define gpio_irq_INTC_CORTEXM4_PRIORITY 7u
#define gpio_irq_INTC_NUMBER 10u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr_INTC_NUMBER 24u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
